### ISSUE TITLE
Create main(or master) structure

### ISSUE THREAD

**Issue by AshbeeKim** [Proj-Caliber/job-market#1]

**Comment by yunyoseob** [comment]
start

**Comment by AshbeeKim** [comment]
Add .gitignore until Jan 6

**DACONS**

**Comment by AshbeeKim** [comment]
전체 브랜치 master랑 동일하게 기본 구성만 끝내면 각자의 repo에서 fetch upstream을 하면 됩니다.
이후 각자의 repo 내 ./.gitignore 중 DACONS/* 앞에 작업할 브랜치에서 sharp로 주석 처리한 뒤, 해당 브랜치의 DACONS 폴더 내에서 작업을 하면 됩니다.

혹시 @yunyoseob README.md는 어떻게 구성할 계획이신가요?

**Comment by AshbeeKim** [comment]
오호 그럼 한번에 정리되기 전, 대략적인 개요를 각자의 스타일대로 개인의 repo내에 README.md에 정리하면 되겠군요 got it!
그럼 기본적인 구조는 현재에서 마무리 되는 것으로 알고 branch별 reviewer가 컨펌하면 merge하고, 해당 issue 닫겠습니다~

**Comment by yunyoseob** [comment]
넹 추가적으로 제가 해야할 일이 있나요?

네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Ashbee ***@***.***>
받는사람: ***@***.***>
참조: "Yun ***@***.***>, ***@***.***>
날짜: 2022. 1. 5 오전 2:01:07
제목: Re: [Proj-Caliber/job-market] Create main(or master) structure (Issue #1)

오호 그럼 한번에 정리되기 전, 대략적인 개요를 각자의 스타일대로 개인의 repo내에 README.md에 정리하면 되겠군요 got it!
그럼 기본적인 구조는 현재에서 마무리 되는 것으로 알고 branch별 reviewer가 컨펌하면 merge하고, 해당 issue 닫겠습니다~

**Comment by AshbeeKim** [comment]
pr #3 확인 후 컨펌? 아니면 의견 제시요ㅎㅎ

**Comment by yunyoseob** [comment]
넵 혹시나 Merge Pull Request 해야하면 알려주세요~

네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Ashbee ***@***.***>
받는사람: ***@***.***>
참조: "Yun ***@***.***>, ***@***.***>
날짜: 2022. 1. 5 오전 2:03:45
제목: Re: [Proj-Caliber/job-market] Create main(or master) structure (Issue #1)

pr #3 확인 후 컨펌? 아니면 의견 제시요ㅎㅎ

**Comment by yunyoseob** [comment]
job-care 브랜치에서 각자 브랜치 하나씩 따서 거기서 작업을 진행할까요? 의견있으면 남겨주세요.

**Comment by AshbeeKim** [comment]
음 마지막까지 상의된 내용이 jobcare만 참가하는 거라면, master를 제외한 브랜치를 지우고 develop을 생성 후 develop에서 다시 branch를 생성하거나 하는 방식으로 진행함이 맞을 듯 합니다. 저는 DB나 cloud를 연습해 볼 겸, 늦게라도 시각화 진행해보고 싶은데, 저와 유사하게 각자 천천히 진행해보고 싶을 대회가 추가적으로 있을 수 있다고 생각됩니다. 말씀해주신 내용처럼 일단 생성된 브랜치를 제거하는 것은 보류하고, 추가적인 브랜치를 생성하고 진행하는 것에 대해 다른 분들 생각은 어떠한가요?

**Comment by yunyoseob** [comment]
그럼 일단 know기반 브랜치만 제거하고 잡케어랑 시각화만 내버려두고 잡케어 내에서도 각자 자유롭게 작업하기 위해 각각 브랜치를 딸까요? 의견 남겨주세요.


네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Ashbee ***@***.***>
받는사람: ***@***.***>
참조: "Yun ***@***.***>, ***@***.***>
날짜: 2022. 1. 8 오전 4:11:43
제목: Re: [Proj-Caliber/job-market] Create main(or master) structure (Issue #1)

음 마지막까지 상의된 내용이 jobcare만 참가하는 거라면, master를 제외한 브랜치를 지우고 develop을 생성 후 develop에서 다시 branch를 생성하거나 하는 방식으로 진행함이 맞을 듯 합니다. 저는 DB나 cloud를 연습해 볼 겸, 늦게라도 시각화 진행해보고 싶은데, 저와 유사하게 각자 천천히 진행해보고 싶을 대회가 추가적으로 있을 수 있다고 생각됩니다. 말씀해주신 내용처럼 일단 생성된 브랜치를 제거하는 것은 보류하고, 추가적인 브랜치를 생성하고 진행하는 것에 대해 다른 분들 생각은 어떠한가요?

**Comment by AshbeeKim** [comment]
@qkrwjdduf159
이미 organization에 push한 내용은 개개인이 fork한 레포 내 ./DACONS의 하위 폴더 혹은 파일로 업로드하기로 했던 내용에서 변경되었나요?

```
> git rm --cached --help
> git stash save --help
```

변경사항이 없다면, rm이나 stash를 참고해보시면 좋을 것 같습니다~

**Comment by AshbeeKim** [comment]
@oliviachchoi @seonhong416 은 브랜치를 이대로 가져가서 각 목적에 맞게끔 checkout한 브랜치에서 진행 내용에 맞게 혹은 담당 내용에 맞게 진행하는 게 나은지 아니면 아예 지우고 develop에서 각자 branch를 따서 진행하는 방법이 괜찮을지 코멘트로 알려주세요

**Comment by seonhong416** [comment]
저는 후자가 좋을거 같습니다!
-----Original Message-----

**Comment by oliviachchoi** [comment]
저는 develop에서 각자 branch를 따서 진행하는게 깔끔할 것 같습니다

**Comment by qkrwjdduf159** [comment]
> @qkrwjdduf159 이미 organization에 push한 내용은 개개인이 fork한 레포 내 ./DACONS의 하위 폴더 혹은 파일로 업로드하기로 했던 내용에서 변경되었나요?
> 
> ```
> > git rm --cached --help
> > git stash save --help
> ```
> 
> 변경사항이 없다면, rm이나 stash를 참고해보시면 좋을 것 같습니다~

감사합니다 한번 시도해 볼게요~
